### ISSUE TITLE
Question / Creative Cloud 2017 / CSInterface.js

### ISSUE THREAD

**Issue by Jolg42** [pravdomil/types-for-adobe#1]
Hi @pravdomil!

I just discovered this repo on Adobe Dev's Slack, this is really cool :+1: 

1. We can now use TypeScript for .jsx if I understand it right?
2. Do you know if someone did the declaration file for "CSInterface.js" for HTML5 panels?
3. How much work do you think is needed approximately to support CC2017?

**Comment by pravdomil** [comment]
1. yes, you write .ts file, which is converted by typescript compiler to .js file, which you can rename to .jsx and launch
2. I have not heard about "CSInterface.js", can you please provide me more info?
3. I'm working on CC2017, but now you can, try to use old types from CC2015

**Comment by naokihada** [comment]
"CSInterface.js" is from here.
  https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_7.x
TypeScript version is here.
  https://github.com/BrightShadow/CSInterface-TS
That's Adobe's CEP plugin (HTML5 + NodeJS + JSX).
 CSInterface.evalScript() can invoke JSX from JS.
There's a TypeScript sample, but not fully integrated with all (or multiple) Adobe apps.
  https://github.com/Adobe-CEP/Samples/tree/master/TypeScript

**Comment by pravdomil** [comment]
for CC2017 I would need XML documentation files that can be found in:
/Library/Application Support/Adobe/Scripting Dictionaries CC/CommonFiles
~/Library/Preferences/ExtendScript Toolkit

extend script toolkit stores the xml file there when you start writing new script

**Comment by Jolg42** [comment]
[Scripting Dictionnaries CC.zip](https://github.com/pravdomil/types-for-adobe/files/1324579/Scripting.Dictionnaries.CC.zip) is what's in my `CommonFiles` folder
It looks like it's the same xml used by Illustrator 2015.3 & 2017.

**Comment by pravdomil** [comment]
@Jolg42 there is more types 2018 types coming
check https://github.com/pravdomil/extendscript-xml-to-typescript/issues/1 how to correct dump xml files
