### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by vespakoen** [pravdomil/Types-for-Adobe#26]
That way people don't necessarily have to install git

**Comment by pravdomil** [comment]
You can run
‘npm i pravdomil/types-for-adobe’
Right?

**Comment by vespakoen** [comment]
Yes, but then it will clone the project from github, when git is not available on the system, it won't work (I found out about this when using the node alpine docker image, which doesn't have git)

See: https://aedtci.mtmograph.com/adobe-extension-tools/extendscript-starter/1/3

**Comment by pravdomil** [comment]
I prefer to leave the repository on GitHub,
because I don’t have to release new version on npm each time I make a change
I have added git to the list of prerequisites

**Comment by pravdomil** [comment]
https://www.npmjs.com/package/types-for-adobe
