### ISSUE TITLE
Merge into DefinitelyTyped

### ISSUE THREAD

**Issue by appsforartists** [pravdomil/Types-for-Adobe#29]
The `@types` namespace has become the canonical place for external typings.  Have you considered migrating this project to https://github.com/DefinitelyTyped/DefinitelyTyped?

cc @atarabi

**Comment by pravdomil** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19046

**Comment by appsforartists** [comment]
:'(
