### ISSUE TITLE
The type definitions for Books.everyItem() are wrong(and probably other everyItem() methods)

### ISSUE THREAD

**Issue by sebastianiorga** [pravdomil/Types-for-Adobe#31]
## Version used
InDesign 2018 index.d.ts with InDesign Creative Cloud 2018. 

I'm using my fork of the repo. All I've really changed is made InDesign 2018 request ScriptUI automatically and deleted various conflicts from InDesign2018/index.d.ts. 

I don't think that has anything to do with the bug.

## TLDR
`app.books.everyItem()` claims to return `Book[]` actually returns `Book`.

## The madness

`app.books` returns a `Books` object. `app.books.everyItem()` claims(at http://jongware.mit.edu/idcs6js/pc_Books.html and in the type defs in `index.d.ts`) that it returns `Book[]`. In fact, it returns `Book`. But a weird `Book` that sort of proxies messages to the underlying `Book` objects. This link explains what they are actually doing: http://www.indiscripts.com/post/2010/06/on-everyitem-part-1. 

So, for instance, `app.books.everyItem() instanceof Book === true`. Mad.

#### Getting an array of `Books`
If you actually want an array of `Book`s you need to call `app.books.everyItem().getElements()`. You can't call `app.books.getElements()`. `getElements()` will return an array when called on a normal single book as well as the object reference book returned by `everyItem()`. An extremely `wat` moment if I ever saw one.

#### Fixing the type signatures
The method signature for `everyItem` should be `Book`. Plus maybe some sort of documentation warning explaining that crazy things are going on when you call that. Maybe even mention needing to chain with `getElements` to get an array.

edit. Thank you very much for this project, by the way. I'm just getting started with ID scripting and it would be a lot more hellish without it.

**Comment by pravdomil** [comment]
Hi, yea that's is know issue.

Those types are fixed in indd 2015 https://github.com/pravdomil/Types-for-Adobe/commit/03a0b47be3e4c7956ec97228a1f53bd44f2a7538

Now I have also fixed indd 2018 https://github.com/pravdomil/Types-for-Adobe/commit/153bb7898c6a3f4e398ad332c19bd36f243a03f3
