### ISSUE TITLE
Use Angular and Types for adobe in same namespace

### ISSUE THREAD

**Issue by StefanRiedmann** [pravdomil/Types-for-Adobe#34]
Hello!
Great package! But in my angular application, I get lots of 'Duplicate' errors. Example:

In my angular service, I do
import 'types-for-adobe/Illustrator/2015.3/index.d';

Then I can use 'app.activeDocument', but the Document members (like 'name') are not accessible. 

Additionally, I get duplicate errors on transpile: 

node_modules/typescript/lib/lib.dom.d.ts (3470,13): Duplicate identifier 'Document'.
node_modules/types-for-adobe/Illustrator/2015.3/index.d.ts (8453,15): Duplicate identifier 'Document'.

What am I doing wrong? 
Thanks
Stefa

**Comment by StefanRiedmann** [comment]
Thank you, but unfortunately Angular doesn't like this...
node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts (25,23): Cannot find name 'Node'.
[together with many others]

I guess I'd have to put all your types into a module, and import it somehow like this:
import * as illustrator from 'types-for-adobe/Illustrator/2015.3/index.d'

I'll try this soon and let you know.

**Comment by pravdomil** [comment]
I would not recommend to mix angular and types-for-adobe, there will be duplicated definitions, for example type in browser `window.document` has type `Document` which will collide with `app.activeDocument` which has same type `Document`

Try to split your repo into Adobe's Extend Script part and Node.js part.

**Comment by StefanRiedmann** [comment]
I followed your advise, and separated the scripts package from the extension package. Thank you for your help!
