### ISSUE TITLE
File object

### ISSUE THREAD

**Issue by bryab** [pravdomil/Types-for-Adobe#36]
Thanks for this library, it is making me not as sad to get back into writing some scripts for AE.

Do you know a way to get Typescript to understand the [Extendscript File object](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/scripting/pdfs/javascript_tools_guide.pdf) -- essentially overriding the default Javascript File object?

For now I am just adding @ts-ignore before all references to the File object...

**Comment by pravdomil** [comment]
Please follow setup guide 
https://github.com/pravdomil/Types-for-Adobe/blob/master/README.md#your-first-script-for-eg-adobe-illustrator
And then File will point to the extend script File.

**Comment by bryab** [comment]
Aha, thanks.

So my understanding is that your target here are single-file scripts.  I'm trying to compile a large "library" of files that i use across all my scripts.

My current thought is to compile all those "library" files in a single `.jsxinc` file.  Then `#import` that .jsxinc before executing my individual scripts.

Preferably we could use proper module imports but I don't think there's a way to get it to work in Extendscript...

**Comment by pravdomil** [comment]
for javascript modules you will need webpack
