### ISSUE TITLE
Photoshop 2015.5: Duplicate static and public declarations

### ISSUE THREAD

**Issue by lm913** [pravdomil/types-for-adobe#9]
https://github.com/pravdomil/types-for-adobe/blob/master/Photoshop/2015.5

Is there a reason for the duplicate declarations in the SolidColor class?

```javascript
declare class SolidColor {
	/**
	 * The CMYK color model.
	 */
	static cmyk: CMYKColor;

	/**
	 * The CMYK color model.
	 */
	cmyk: CMYKColor;

	/**
	 * The grayscale color model.
	 */
	static gray: GrayColor;

	/**
	 * The grayscale color model.
	 */
	gray: GrayColor;
```

**Comment by pravdomil** [comment]
‘’’ts
alert(SolidColor.gray);
alert((new SolidColor()).gray);
‘’’

**Comment by lm913** [comment]
Ah I see, that makes sense. In the previous typings I was using for Photoshop everything was set up through interfaces and the classes implemented those interfaces so I was accustomed to that behaviour
